printf '%s\n' user-top >> "$KR_TEST_ORDER"

PS1='KR> '
HISTFILE=
KR_TEST_USER_CONFIGURATION=1

export ATUIN_CONFIG_DIR="$HOME/.config/atuin"
eval "$("$KR_STACK_ATUIN/atuin" init bash --disable-up-arrow)"
printf '%s\n' stack >> "$KR_TEST_ORDER"

bind '"\eq": "kr-user-binding-ran"'

printf '%s\n' user-bottom >> "$KR_TEST_ORDER"
# {kalareach-entry}
