//! The pinned `xterm-256color` capability values.
//!
//! The managed environment supplies this database rather than trusting whatever the host has
//! installed, so the capabilities an application reads and the answers the query broker gives come
//! from the same place.
//!
//! Source: the ncurses `xterm-256color` entry, with the kr-vt/1 deltas recorded in
//! `docs/terminal/README.md`. `arguments` is one representative parameter set; the class-coverage
//! check expands the capability's own value with them and lexes the result, so every advertised
//! capability is proved to have a class rather than assumed to have one.

use super::expand::Param;
use super::{Direction, StringCapability};

pub(crate) const BOOLEANS: &[&str] = &[
    "AX", "RGB", "Tc", "XT", "am", "bce", "ccc", "km", "mir", "msgr", "npc", "xenl",
];

pub(crate) const NUMBERS: &[(&str, i32)] = &[
    ("colors", 256),
    ("cols", 80),
    ("it", 8),
    ("lines", 24),
    ("pairs", 32767),
];

pub(crate) const STRINGS: &[StringCapability] = &[
    StringCapability {
        name: "BD",
        value: "\x1b[?2004l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "BE",
        value: "\x1b[?2004h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "Cr",
        value: "\x1b]112\x07",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "Cs",
        value: "\x1b]12;%p1%s\x07",
        arguments: &[Param::Text("rgb:12/34/56")],
        direction: Direction::Output,
    },
    StringCapability {
        name: "E3",
        value: "\x1b[3J",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "Ms",
        value: "\x1b]52;%p1%s;%p2%s\x07",
        arguments: &[Param::Text("c"), Param::Text("aGVsbG8=")],
        direction: Direction::Output,
    },
    StringCapability {
        name: "PE",
        value: "\x1b[201~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "PS",
        value: "\x1b[200~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "Se",
        value: "\x1b[0 q",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "Smulx",
        value: "\x1b[4:%p1%dm",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "Ss",
        value: "\x1b[%p1%d q",
        arguments: &[Param::Number(2)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "acsc",
        value: "``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~",
        arguments: &[],
        direction: Direction::Data,
    },
    StringCapability {
        name: "bel",
        value: "\x07",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "blink",
        value: "\x1b[5m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "bold",
        value: "\x1b[1m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cbt",
        value: "\x1b[Z",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "civis",
        value: "\x1b[?25l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "clear",
        value: "\x1b[H\x1b[2J",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cnorm",
        value: "\x1b[?12l\x1b[?25h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cr",
        value: "\x0d",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "csr",
        value: "\x1b[%i%p1%d;%p2%dr",
        arguments: &[Param::Number(0), Param::Number(23)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cub",
        value: "\x1b[%p1%dD",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cub1",
        value: "\x08",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cud",
        value: "\x1b[%p1%dB",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cud1",
        value: "\x0a",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cuf",
        value: "\x1b[%p1%dC",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cuf1",
        value: "\x1b[C",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cup",
        value: "\x1b[%i%p1%d;%p2%dH",
        arguments: &[Param::Number(5), Param::Number(10)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cuu",
        value: "\x1b[%p1%dA",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cuu1",
        value: "\x1b[A",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "cvvis",
        value: "\x1b[?12;25h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "dch",
        value: "\x1b[%p1%dP",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "dch1",
        value: "\x1b[P",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "dim",
        value: "\x1b[2m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "dl",
        value: "\x1b[%p1%dM",
        arguments: &[Param::Number(2)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "dl1",
        value: "\x1b[M",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ech",
        value: "\x1b[%p1%dX",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ed",
        value: "\x1b[J",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "el",
        value: "\x1b[K",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "el1",
        value: "\x1b[1K",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "flash",
        value: "\x1b[?5h\x1b[?5l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "home",
        value: "\x1b[H",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "hpa",
        value: "\x1b[%i%p1%dG",
        arguments: &[Param::Number(5)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ht",
        value: "\x09",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "hts",
        value: "\x1bH",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ich",
        value: "\x1b[%p1%d@",
        arguments: &[Param::Number(3)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "il",
        value: "\x1b[%p1%dL",
        arguments: &[Param::Number(2)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "il1",
        value: "\x1b[L",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ind",
        value: "\x0a",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "indn",
        value: "\x1b[%p1%dS",
        arguments: &[Param::Number(2)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "initc",
        value: "\x1b]4;%p1%d;rgb:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\x1b\x5c",
        arguments: &[
            Param::Number(7),
            Param::Number(1000),
            Param::Number(500),
            Param::Number(250),
        ],
        direction: Direction::Output,
    },
    StringCapability {
        name: "invis",
        value: "\x1b[8m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "is2",
        value: "\x1b[!p\x1b[4l\x1b>",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "kDC",
        value: "\x1b[3;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDC3",
        value: "\x1b[3;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDC4",
        value: "\x1b[3;4~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDC5",
        value: "\x1b[3;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDC6",
        value: "\x1b[3;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDC7",
        value: "\x1b[3;7~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDN",
        value: "\x1b[1;2B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDN3",
        value: "\x1b[1;3B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDN4",
        value: "\x1b[1;4B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDN5",
        value: "\x1b[1;5B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDN6",
        value: "\x1b[1;6B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kDN7",
        value: "\x1b[1;7B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kEND",
        value: "\x1b[1;2F",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kEND3",
        value: "\x1b[1;3F",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kEND4",
        value: "\x1b[1;4F",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kEND5",
        value: "\x1b[1;5F",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kEND6",
        value: "\x1b[1;6F",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kEND7",
        value: "\x1b[1;7F",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kHOM",
        value: "\x1b[1;2H",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kHOM3",
        value: "\x1b[1;3H",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kHOM4",
        value: "\x1b[1;4H",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kHOM5",
        value: "\x1b[1;5H",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kHOM6",
        value: "\x1b[1;6H",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kHOM7",
        value: "\x1b[1;7H",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kIC",
        value: "\x1b[2;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kIC3",
        value: "\x1b[2;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kIC4",
        value: "\x1b[2;4~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kIC5",
        value: "\x1b[2;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kIC6",
        value: "\x1b[2;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kIC7",
        value: "\x1b[2;7~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kLFT",
        value: "\x1b[1;2D",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kLFT3",
        value: "\x1b[1;3D",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kLFT4",
        value: "\x1b[1;4D",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kLFT5",
        value: "\x1b[1;5D",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kLFT6",
        value: "\x1b[1;6D",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kLFT7",
        value: "\x1b[1;7D",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kNXT",
        value: "\x1b[6;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kNXT3",
        value: "\x1b[6;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kNXT4",
        value: "\x1b[6;4~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kNXT5",
        value: "\x1b[6;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kNXT6",
        value: "\x1b[6;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kNXT7",
        value: "\x1b[6;7~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kPRV",
        value: "\x1b[5;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kPRV3",
        value: "\x1b[5;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kPRV4",
        value: "\x1b[5;4~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kPRV5",
        value: "\x1b[5;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kPRV6",
        value: "\x1b[5;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kPRV7",
        value: "\x1b[5;7~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kRIT",
        value: "\x1b[1;2C",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kRIT3",
        value: "\x1b[1;3C",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kRIT4",
        value: "\x1b[1;4C",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kRIT5",
        value: "\x1b[1;5C",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kRIT6",
        value: "\x1b[1;6C",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kRIT7",
        value: "\x1b[1;7C",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kUP",
        value: "\x1b[1;2A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kUP3",
        value: "\x1b[1;3A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kUP4",
        value: "\x1b[1;4A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kUP5",
        value: "\x1b[1;5A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kUP6",
        value: "\x1b[1;6A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kUP7",
        value: "\x1b[1;7A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kb2",
        value: "\x1bOE",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kbs",
        value: "\x08",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kcbt",
        value: "\x1b[Z",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kcub1",
        value: "\x1bOD",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kcud1",
        value: "\x1bOB",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kcuf1",
        value: "\x1bOC",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kcuu1",
        value: "\x1bOA",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kdch1",
        value: "\x1b[3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kend",
        value: "\x1bOF",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kent",
        value: "\x1bOM",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf1",
        value: "\x1bOP",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf10",
        value: "\x1b[21~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf11",
        value: "\x1b[23~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf12",
        value: "\x1b[24~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf13",
        value: "\x1b[1;2P",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf14",
        value: "\x1b[1;2Q",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf15",
        value: "\x1b[1;2R",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf16",
        value: "\x1b[1;2S",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf17",
        value: "\x1b[15;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf18",
        value: "\x1b[17;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf19",
        value: "\x1b[18;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf2",
        value: "\x1bOQ",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf20",
        value: "\x1b[19;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf21",
        value: "\x1b[20;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf22",
        value: "\x1b[21;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf23",
        value: "\x1b[23;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf24",
        value: "\x1b[24;2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf25",
        value: "\x1b[1;5P",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf26",
        value: "\x1b[1;5Q",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf27",
        value: "\x1b[1;5R",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf28",
        value: "\x1b[1;5S",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf29",
        value: "\x1b[15;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf3",
        value: "\x1bOR",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf30",
        value: "\x1b[17;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf31",
        value: "\x1b[18;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf32",
        value: "\x1b[19;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf33",
        value: "\x1b[20;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf34",
        value: "\x1b[21;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf35",
        value: "\x1b[23;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf36",
        value: "\x1b[24;5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf37",
        value: "\x1b[1;6P",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf38",
        value: "\x1b[1;6Q",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf39",
        value: "\x1b[1;6R",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf4",
        value: "\x1bOS",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf40",
        value: "\x1b[1;6S",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf41",
        value: "\x1b[15;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf42",
        value: "\x1b[17;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf43",
        value: "\x1b[18;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf44",
        value: "\x1b[19;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf45",
        value: "\x1b[20;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf46",
        value: "\x1b[21;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf47",
        value: "\x1b[23;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf48",
        value: "\x1b[24;6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf49",
        value: "\x1b[1;3P",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf5",
        value: "\x1b[15~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf50",
        value: "\x1b[1;3Q",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf51",
        value: "\x1b[1;3R",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf52",
        value: "\x1b[1;3S",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf53",
        value: "\x1b[15;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf54",
        value: "\x1b[17;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf55",
        value: "\x1b[18;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf56",
        value: "\x1b[19;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf57",
        value: "\x1b[20;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf58",
        value: "\x1b[21;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf59",
        value: "\x1b[23;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf6",
        value: "\x1b[17~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf60",
        value: "\x1b[24;3~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf61",
        value: "\x1b[1;4P",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf62",
        value: "\x1b[1;4Q",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf63",
        value: "\x1b[1;4R",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf7",
        value: "\x1b[18~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf8",
        value: "\x1b[19~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kf9",
        value: "\x1b[20~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "khome",
        value: "\x1bOH",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kich1",
        value: "\x1b[2~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kind",
        value: "\x1b[1;2B",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kmous",
        value: "\x1b[M",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "knp",
        value: "\x1b[6~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kpp",
        value: "\x1b[5~",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "kri",
        value: "\x1b[1;2A",
        arguments: &[],
        direction: Direction::Input,
    },
    StringCapability {
        name: "op",
        value: "\x1b[39;49m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rc",
        value: "\x1b8",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rev",
        value: "\x1b[7m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ri",
        value: "\x1bM",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rin",
        value: "\x1b[%p1%dT",
        arguments: &[Param::Number(2)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "ritm",
        value: "\x1b[23m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmacs",
        value: "\x1b(B",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmam",
        value: "\x1b[?7l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmcup",
        value: "\x1b[?1049l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmir",
        value: "\x1b[4l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmkx",
        value: "\x1b[?1l\x1b>",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmm",
        value: "\x1b[?1034l",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmso",
        value: "\x1b[27m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmul",
        value: "\x1b[24m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rmxx",
        value: "\x1b[29m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rs1",
        value: "\x1bc",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "rs2",
        value: "\x1b[!p\x1b[4l\x1b>",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "sc",
        value: "\x1b7",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "setab",
        value: "\x1b[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m",
        arguments: &[Param::Number(200)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "setaf",
        value: "\x1b[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m",
        arguments: &[Param::Number(200)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "setrgbb",
        value: "\x1b[48:2::%p1%d:%p2%d:%p3%dm",
        arguments: &[Param::Number(12), Param::Number(34), Param::Number(56)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "setrgbf",
        value: "\x1b[38:2::%p1%d:%p2%d:%p3%dm",
        arguments: &[Param::Number(12), Param::Number(34), Param::Number(56)],
        direction: Direction::Output,
    },
    StringCapability {
        name: "sgr",
        value: "%?%p9%t\x1b(0%e\x1b(B%;\x1b[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m",
        arguments: &[
            Param::Number(0),
            Param::Number(1),
            Param::Number(0),
            Param::Number(0),
            Param::Number(0),
            Param::Number(1),
            Param::Number(0),
            Param::Number(0),
            Param::Number(0),
        ],
        direction: Direction::Output,
    },
    StringCapability {
        name: "sgr0",
        value: "\x1b(B\x1b[m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "sitm",
        value: "\x1b[3m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smacs",
        value: "\x1b(0",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smam",
        value: "\x1b[?7h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smcup",
        value: "\x1b[?1049h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smir",
        value: "\x1b[4h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smkx",
        value: "\x1b[?1h\x1b=",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smm",
        value: "\x1b[?1034h",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smso",
        value: "\x1b[7m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smul",
        value: "\x1b[4m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "smxx",
        value: "\x1b[9m",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "tbc",
        value: "\x1b[3g",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "u6",
        value: "\x1b[%i%d;%dR",
        arguments: &[],
        direction: Direction::Report,
    },
    StringCapability {
        name: "u7",
        value: "\x1b[6n",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "u8",
        value: "\x1b[?62;22c",
        arguments: &[],
        direction: Direction::Report,
    },
    StringCapability {
        name: "u9",
        value: "\x1b[c",
        arguments: &[],
        direction: Direction::Output,
    },
    StringCapability {
        name: "vpa",
        value: "\x1b[%i%p1%dd",
        arguments: &[Param::Number(5)],
        direction: Direction::Output,
    },
];
