//! The trust a build commits, and where the official repository is.
//!
//! Generated by `scripts/sync-bundled-plugins.sh`; change the constants there and run it.

/// Where a host that seeds from the bundle fetches the official repository's metadata.
pub const OFFICIAL_METADATA_URL: &str = "https://plugins.reach.kala.to/metadata/";

/// Where it fetches the official repository's targets.
pub const OFFICIAL_TARGETS_URL: &str = "https://plugins.reach.kala.to/targets/";

/// The root key identifiers a release trusts without the owner. Empty until the production
/// root exists, so a release build refuses every seed bundle.
pub const PRODUCTION_ROOT_KEYS: &[&str] = &[];

/// The signatures of those keys a production root has to carry.
pub const PRODUCTION_ROOT_THRESHOLD: u64 = 1;

/// The root key identifiers of the development lineage, trusted by a build with debug
/// assertions. The keys are derived from a published phrase and anybody can sign with them.
pub const DEVELOPMENT_ROOT_KEYS: &[&str] = &[
    "22a99bda605726730776823e26da03b178524617baccaee1a75ad8a67fb41eca",
];
