//! Generates the many functions that make this component slow to compile.
//!
//! The point of the fixture is a component whose compilation takes long enough to measure, so that
//! a test can show a call deadline does not contain it. Size is what makes a compile slow, and
//! generating the size is more honest than committing a megabyte of repetitive source.

use std::fmt::Write as _;

/// How many functions to generate.
///
/// Each one is a short chain of arithmetic whose seed passes through `black_box`, so the optimiser
/// cannot fold the chain into a constant and delete it. Together they are a few hundred kilobytes
/// of Wasm and enough work to make a cold compile visible against a 10 ms deadline.
const FUNCTIONS: usize = 4_000;

/// How many arithmetic steps each function performs.
const STEPS: usize = 24;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let out_dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR for a build script");
    let mut source = String::new();
    source.push_str("// Generated by build.rs. Every function is reachable from `work` below.\n");
    for index in 0..FUNCTIONS {
        let _ = writeln!(source, "#[inline(never)]");
        let _ = writeln!(source, "fn step_{index}(seed: u64) -> u64 {{");
        let _ = writeln!(
            source,
            "    let mut value = core::hint::black_box(seed) ^ {};",
            index as u64 * 0x9E37_79B9
        );
        for step in 0..STEPS {
            let _ = writeln!(
                source,
                "    value = value.rotate_left({}).wrapping_mul(0x{:04x}).wrapping_add({});",
                (step % 63) as u32 + 1,
                (step * 7 + 3) | 1,
                step as u64 * 31 + 1
            );
        }
        let _ = writeln!(source, "    value");
        let _ = writeln!(source, "}}");
    }
    source.push_str("/// Calls every generated function once.\npub fn work(seed: u64) -> u64 {\n    let mut value = seed;\n");
    for index in 0..FUNCTIONS {
        let _ = writeln!(source, "    value = step_{index}(value);");
    }
    source.push_str("    value\n}\n");
    std::fs::write(std::path::Path::new(&out_dir).join("generated.rs"), source)
        .expect("the generated source is written");
}
