print -r -- user-top >> "$KR_TEST_ORDER"

PROMPT='KR> '
setopt no_beep
unsetopt zle_rprompt_indent 2>/dev/null
HISTFILE=
typeset -g KR_TEST_USER_CONFIGURATION=1

export ATUIN_CONFIG_DIR="$HOME/.config/atuin"
eval "$("$KR_STACK_ATUIN/atuin" init zsh --disable-up-arrow)"
print -r -- stack >> "$KR_TEST_ORDER"

kr-user-widget() { BUFFER='kr-user-binding-ran'; CURSOR=$#BUFFER }
zle -N kr-user-widget
bindkey '^[q' kr-user-widget

print -r -- user-bottom >> "$KR_TEST_ORDER"
# {kalareach-entry}
